name: flutter_mood_diary
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter
  # UI
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1
  blobs: ^2.0.0
  
  # DI
  get_it: ^7.2.0
  injectable: ^1.5.3

  # 

  # Starter kit
  pocket:
    path: /Users/zoro/dev/flutter-projects/starter_kit_flutter/pocket
  # pocket:
  #   git:
  #     url: https://github.com/jamescardona11/starter_kit_flutter.git
  #     path: pocket/
      # ref: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
